### ISSUE TITLE
code.highcharts.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [Ultimate-Hosts-Blacklist/xorcan_tuerk_ad_list#1]
code.highcharts.com is on the whitelisted.list but it's still in mitchellkrogza/Ultimate.Hosts.Blacklist/blob/master/domains/domains0.list

**Comment by funilrys** [comment]
Closing as I explained what is the purpose of `whitelisted.list` at https://github.com/Ultimate-Hosts-Blacklist/dev-center/issues/44#issuecomment-621160133

Let me know if it's not clear!
